name: release

on:

  workflow_dispatch:
    inputs:
      bump:
        description: 'Bump version'
        required: true


jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/release/v') }}
    runs-on: ubuntu-latest
    steps:
      # This should create an empty release draft
      # TODO: get artifacts from Buildkite to be attached to the draft
      # Task: https://cardanofoundation.atlassian.net/browse/ADP-2502
      - name: '🚀 Release'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          # fail_on_unmatched_files: true
          # files: |
          #   *.tar.gz
          #   *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bump_sh:
    runs-on: ubuntu-latest
    steps:
      - name: '📥 Checkout repository'
        uses: actions/checkout@v4.1.1


      - name: 'Set up Ruby'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: 'Install dependencies'
        run: |
          gem install bump-cli
      - name: 'Update Release in Bump.sh'
        run: './scripts/gh/update-bump.sh'
        env:
          BUMP_SH_DOC_ID: ${{ secrets.BUMP_SH_DOC_ID }}
          BUMP_SH_TOKEN: ${{ secrets.BUMP_SH_TOKEN }}
          WALLET_VERSION:
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixpkgs-21.11-darwin
      - name: 'Show latest changes from Bump.sh'
        run: './scripts/gh/show-bump.sh'
